# Generated by Django 3.1 on 2021-01-12 01:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('challenge', '0002_auto_20210112_0100'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='challenge',
            name='members',
        ),
    ]
