# Generated by Django 3.1 on 2021-01-12 01:27

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('challenge', '0003_remove_challenge_members'),
    ]

    operations = [
        migrations.AddField(
            model_name='challenge',
            name='members',
            field=models.ManyToManyField(related_name='challenge_challenge_related', related_query_name='challenge_challenges', to=settings.AUTH_USER_MODEL),
        ),
    ]
