# Generated by Django 3.1 on 2021-01-12 01:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('challenge', '0004_challenge_members'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='challenge',
            name='end',
        ),
        migrations.RemoveField(
            model_name='challenge',
            name='start',
        ),
    ]
