# Generated by Django 3.1 on 2021-01-13 00:49

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('challenge', '0005_auto_20210112_0143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='challenge',
            name='members',
            field=models.ManyToManyField(blank=True, related_name='challenge_challenge_related', related_query_name='challenge_challenges', to=settings.AUTH_USER_MODEL),
        ),
    ]
