# Generated by Django 3.1 on 2021-01-13 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('challenge', '0006_auto_20210113_0049'),
    ]

    operations = [
        migrations.RenameField(
            model_name='challenge',
            old_name='creator',
            new_name='created_by',
        ),
    ]
