# Generated by Django 3.1 on 2021-01-18 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenge', '0007_auto_20210113_1122'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='challengeactivity',
            constraint=models.UniqueConstraint(fields=('challenge', 'activity'), name='unique challenge activity'),
        ),
    ]
