# Generated by Django 3.1 on 2021-01-20 01:05

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('challenge', '0008_auto_20210118_1916'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('activity', models.CharField(choices=[('WALKING', 'Walking'), ('CYCLING', 'Cycling'), ('RUNNING', 'Running')], default='CYCLING', max_length=20)),
                ('distance', models.IntegerField()),
                ('hours', models.PositiveIntegerField()),
                ('minutes', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(60)])),
                ('challenge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='challenge.challenge')),
            ],
        ),
    ]
