# Generated by Django 3.1 on 2021-01-20 01:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('challenge', '0009_activity'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ChallengeActivity',
        ),
    ]
