# Generated by Django 3.1 on 2021-01-20 01:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenge', '0010_delete_challengeactivity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='hours',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='activity',
            name='minutes',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(60)]),
        ),
    ]
