# Generated by Django 3.1 on 2021-01-20 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenge', '0011_auto_20210120_0125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='distance',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=6),
        ),
    ]
