# Generated by Django 3.1 on 2021-01-20 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenge', '0014_activity_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='measure',
            field=models.CharField(choices=[('KM', 'Km'), ('MILES', 'Miles')], default='MILES', max_length=5),
        ),
    ]
