# Generated by Django 3.1 on 2021-02-01 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('challenge', '0015_activity_measure'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='challenge',
        ),
    ]
