# Generated by Django 3.1 on 2021-02-01 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenge', '0016_remove_activity_challenge'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='challenges',
            field=models.ManyToManyField(related_name='challenge_activity_related', related_query_name='challenge_activitys', to='challenge.Challenge'),
        ),
    ]
