# Generated by Django 3.1 on 2021-02-02 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenge', '0017_activity_challenges'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='challenges',
            field=models.ManyToManyField(blank=True, related_name='challenge_activity_related', related_query_name='challenge_activitys', to='challenge.Challenge'),
        ),
    ]
